# Este fichero sirve para crear en local la máquina virtual que alojará ambos
# microservicios:

Vagrant.configure("2") do |config|
  # Como imagen utilizaremos el box de Ubuntu 18.04 LTS:
  config.vm.box = "ubuntu/bionic64"
  # Redirigimos los puertos de la máquina anfitriona a la máquina virtual:
  config.vm.network "forwarded_port", guest: 22,   host:2222
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.define "gp_local" do |gestionpedidos|
    gestionpedidos.vm.provision "ansible" do |ansible|
        ansible.inventory_path = "ansible_hosts.ini"
        # ansible.verbose = 'vvv'
        ansible.playbook = "../playbook.yml"
    end


    # Especificamos la memoria que utilizará y el número de cores: 4GB y 2 cores
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 3
    end
  end
end