# Lenguaje de programación
language: node_js

# Seleccionar versiones a testear
node_js:
  - "v8.16.2"

# Instalar dependencias
install:
  - npm ci
  
# Mantener el caché npm para acelerar las instalaciones
cache:
  directories:
    - "$HOME/.npm"

# Ejecutar tests
# Se llamará a la orden escrita en el apartado test
# del archivo package.json.
script:
  - npm test
