# Este playbook será llamado automáticamente desde el Vagrantfile para crear
# la máquina en local y el Vagrantfile para crearla en Azure
---
- hosts: all
  remote_user: toniMR
  # Permitir escalada de privilegios
  become: yes
  # Roles utilizados
  roles:
    # Instalar docker con un rol descargado desde Ansible galaxy
    - geerlingguy.docker

  # Especificamos las tareas del playbook:
  tasks:
    # Actualizar sistema
    - name: Apt | Update
      apt:
        update_cache: 'yes'


    # Instalamos pip para poder ejecutar la tarea siguiente:
    - name: Apt | Install python3-pip
      apt:
        name: python3-pip
        state: present
        

    # Instalamos el módulo de python "docker". Esto nos permitirá
    # ejecutar las órdenes de Ansible relacionadas con docker:
    - name: Pip | Install docker python module
      pip:
        name: docker


    # Descargar la imagen desde Docker Hub del microservicio Productos:
    - name: Docker | Pull productos image
      docker_image:
        name: tonimr/cc-gestion-productos:productos
        source: pull
        

    # Descargar la imagen desde Docker Hub del microservicio Pedidos:
    - name: Docker | Pull pedidos image
      docker_image:
        name: tonimr/cc-gestion-productos:pedidos
        source: pull

    
    # Copiar los ficheros .env de cada microservicio para establecer
    # las variables de entorno necesarias.
    - name: Env | copy productos env_file
      copy:
        src: ../.env_productos
        dest: /etc/.env_productos

    - name: Env | copy pedidos env_file
      copy:
        src: ../.env_pedidos
        dest: /etc/.env_pedidos

    
    # Ejecutar el contenedor de productos:
    - name: Docker | Run productos container
      docker_container:
        name: productos
        image: tonimr/cc-gestion-productos:productos
        auto_remove: yes
        detach: yes
        # Publicar el puerto 8080 para poder acceder desde el anfitrion
        # al contenedor desde ese puerto
        published_ports: 8080:8080
        # Indicar la ruta del archivo .env de los productos:
        env_file: /etc/.env_productos


    # Ejecutar el contenedor de pedidos:
    - name: Docker | Run pedidos container
      docker_container:
        name: pedidos
        image: tonimr/cc-gestion-productos:pedidos
        auto_remove: yes
        detach: yes
        # Publicar el puerto 8000 para poder acceder desde el anfitrion
        # al contenedor desde ese puerto
        published_ports: 8000:8000
        # Indicar la ruta del archivo .env de los productos:
        env_file: /etc/.env_pedidos